name: mypy
description: Setup Python, install dependencies in given requirements.txt files, and run mypy

inputs:
  python-version:
    description: Version of python to setup
    default: '3.10'
  requirements-txt:
    description: Relative path to requirements.txt file. Wildcards can be submitted as well
    default: null
  build-command:
    description: Build command to be executed prior to installing and running mypy
    default: null
  mypy-version:
    description: Version of mypy to setup, defaulting to latest
    default: null
  args:
    description: Args for mypy
    default: --exclude build --exclude docs --hide-column-numbers .

runs:
  using: composite
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Set up Python version ${{ inputs.python-version }}
      uses: GenapsysInc/internal-actions/reusable-actions/setup-python@main
      with:
        python-version: ${{ inputs.python-version }}
        requirements-txt: ${{ inputs.requirements-txt }}
        build-command: ${{ inputs.build-command }}
    - name: add mypy annotator
      uses: pr-annotators/mypy-pr-annotator@v1.0.0
    - name: Install mypy
      run: pip install mypy${{ (inputs.mypy-version && '==') || '' }}${{ inputs.mypy-version }}
      shell: bash
    - name: Run mypy
      run: mypy ${{ inputs.args }}
      shell: bash
